### PR TITLE
Switch from requirement.txt to environment.yml

### PR DESCRIPTION
**Pull request by danielhollas**
Switching from `requirements.txt` to Conda environment file `environment.yml` further reduces the CI times since we can use cache. On a cache hit, the whole CI run now take  ~1m 30 (2m on cache miss). Furthermore, it is possible to specify both conda and pip dependencies in the environment file, which leads to massive simplification -- the whole environment specification is now contained in a single file (except for Julia et al).

Other changes:
 - move the remaining install scripts from `scripts/` to root dir
 - further cleanup of install scripts
 - add MACE install and tests to Github CI

### CODE REVIEW

**Comment by danielhollas** [comment]
@juraskov this is ready for review

**Review by juraskov — COMMENTED** [review]
We should modify the README.md file before we approve the changes. The installation is written for install.sh file which was removed and the instructions are not up to date.

**Comment by danielhollas** [comment]
Thank you for the README update, this should be good to go. :rocket: 
(prepac for the last two commits)

**Review by juraskov — APPROVED** [review]
Looks good, now the installation is very clear. TODO: We should test also Nequip at some point.

**Pull request merged**
